# Lista declarativa; o personalizador não deve instalar sem verificar e confirmar.
brew "zsh"
brew "starship"
brew "zoxide"
brew "fzf"
brew "ripgrep"
brew "fd"
brew "bat"
brew "eza"
brew "git"
brew "yazi"
